spring:
  zipkin:
    base-url: http://zipkin-service:9411/
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672
queue:
  
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  health:
      circuitbreakers:
          enabled: true
  endpoint:
    health:
      show-details: always
info:
  author: Marcelo A. P. Ramos
  mail: marceloxpaduan@gmail.com
server:
  port: ${PORT:9999}

message: Generica
