server:
  port: 8085
  servlet:
    context-path: /catalogo/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/catalogo
    url: jdbc:mysql://host.docker.internal:3306/serie
    username: root
    password: colar1414 
