server:
  port: 8085
  servlet:
    context-path: /catalogo/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db-catalogo:3306/catalogo
    username: root
    password: colar1414
