server:
  port: 8080
spring:  
  cloud:
    gateway:
      routes:
        - id: jogosRoute
          uri: lb://JOGOS
          predicates:
           - Path=/jogos/**
        - id: bibliotecaRoute
          uri: lb://BIBLIOTECA
          predicates:
           - Path=/biblioteca/**
        - id: musicaRoute
          uri: lb://MUSICA
          predicates:
           - Path=/musica/**
        - id: playlistRoute
          uri: lb://PLAYLIST
          predicates:
           - Path=/playlist/**
