server:
  port: 8086
  servlet:
    context-path: /movie/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/movie
    #url: jdbc:mysql://localhost:3306/movie
    username: root
    password: colar1414
